### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by magneticscrolls** [gstream/LibAudioStreaming2IceCast#1]
Hi there,

Thank you for providing this library, very much appreciated!

I have used the liblibaudiostream.a from your iOS-Icecast-Client project to successfully open and send to an icecast server.  But am having an connection issue after my session is completed.

So I have being trying to compile this project and currently getting these compilation errors:

**Compile vbrquantize.c
/BlueJayAudioLib/libaudiostream/liblame/vbrquantize.c:367:5: Implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)'

/BlueJayAudioLib/libaudiostream/liblame/vbrquantize.c:993:5: Implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))'**

Currently using Xcode 8.1 on OSX 10.12.1

Any help would be greatly appreciated!
Dave

**Comment by gstream** [comment]
thanks for using this library. I am out of home for now.
I will check this library on new xcode version again when i back to home, this evening. thanks

**Comment by magneticscrolls** [comment]
Awesome, thank you :)

Btw. The only change I made to the project was to the include paths for my
local machine.

**Comment by magneticscrolls** [comment]
Hi there,

Just wondered if you would be interested in doing a few hours work for me?
Willing to pay you for the time spent.

Would like to get this project compiled under the latest Xcode.

Best regards
Dave

**Comment by gstream** [comment]
hey, sorry my absence.

did you solve your issue by yourrself ?

if not, then i can support you.

**Comment by magneticscrolls** [comment]
Hi there,

That's quite ok.   I've still haven't been able to compile the project
under Xcode 8.1
(see screenshot)

**Comment by gstream** [comment]
i can't see any screenshot
can you send me screenshot ?

**Comment by magneticscrolls** [comment]
Here is the project (zip).   The only thing I changed was the include paths
to the project-dir'

Also the screenshot.

**Comment by gstream** [comment]
where is project link ?

**Comment by magneticscrolls** [comment]
Can you see the AudioLib.zip file attached to the last email?

**Comment by gstream** [comment]
I can't see. there is no attached link or file.

**Comment by gstream** [comment]
Let me try with github project.

**Comment by magneticscrolls** [comment]
Just sent you a dropbox link to the project (2mb)

**Comment by gstream** [comment]
Will update you soon

**Comment by magneticscrolls** [comment]
Cool, thank you for looking at this :)

**Comment by magneticscrolls** [comment]
Hi there,

Sorry to bother you, just wondered if you have had a chance to look at the
project?

Best regards
Dave

**Comment by gstream** [comment]
Will update this weekend.

**Comment by magneticscrolls** [comment]
I've got it compiling now, so don't worry.  Thanks anyway

**Comment by gstream** [comment]
Great. Thanks
